language: erlang
script: "make compile"
otp_release:
  - R16B
#  - R15B02
#  - R15B01
#  - R14B04
#  - R14B03

env:
  global:
   - secure: "JLS6CRFJkMhomRhpDvEnJG/PVd8xs2CLsb82ASNNIgHenSxQ+lBBHRSWd+vIJeASNA5kOJ2XylhdYpqy+HklsEFov0AIJZEUDQYn0h2uh42jHDhw6QTCUda0bY64Lrlvo1Trzo1XtDID/NR8G2sSJckfncNPM0eJv102CTcxn4U="
   - GH_OWNER: projectcs13
   - GH_PROJECT_NAME: erlang-travis-test

after_success:
  - git submodule add -b develop https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} stage > /dev/null
  - git submodule add -b staging https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} stage > /dev/null
  - cd stage
  - git branch -a
  - git checkout develop
  - git merge staging
  - git push
