language: erlang
script: "make compile"
otp_release:
  - R16B
#  - R15B02
#  - R15B01
#  - R14B04
#  - R14B03

env:
  global:
    secure: "VPaTPI7jGrNBvTEgiFF0Dr2i1hNCw1wrTOI16MIdye0hfDB0a6Lj1pYPJkuWbgxJ4oPMGYkHX1+6GLvzYaBabEiM2ErptNNtt5YUCMvOVPfvZJP4HC3rKhA7XqlBT3MJeeGg1Ny6kw29lUBxgbLKVso+mleq25nPQi4n+a7+5kc="
    GH_OWNER: automatic
    GH_PROJECT_NAME: erlang-travis-test

after_success:
  - git clone https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} > /dev/null 2>&1
  - git checkout develop
  - git merge staging
