language: erlang
script: "make compile"
otp_release:
  - R16B
  - R15B02
  - R15B01
  - R14B04
  - R14B03
before_script:
  - git clone --depth=50 --branch=develop git://github.com/projectcs13/erlang-travis-test.git projectcs13/erlang-travis-test
after_success:
  - git branch -a
